### ISSUE TITLE
Hey on the rebuilt version in the onua level I was able to play and now I cant even press the Play Game button without it crashing with this error. "Unhandled Exception: c0000005 At address: 65746233".

### ISSUE THREAD

**Issue by Xhanesage** [TheLegendOfMataNui/game-issues#273] opened 2019-10-10 00:45 UTC
**Remember to add the following information:**

**Build Version:**

Either 0.006 Alpha or "Beta" October 23, 2001

**Steps to Reproduce:**

Give steps to reproduce here.

**Comment by ShadowOfNight** [comment] 2019-10-10 00:47
Crashing with what?  Was there an image you attached?

**Comment by Xhanesage** [comment] 2019-10-10 00:50
sorry it posted before I had finished.

**Comment by ShadowOfNight** [comment] 2019-10-10 00:51
No worries.  Can't say I've seen this crash before either.  Interesting.

**Comment by Xhanesage** [comment] 2019-10-10 00:53
Think I should reinstall and see if it happens again?

**Comment by ShadowOfNight** [comment] 2019-10-10 00:54
Can you upload your save file here?  It may be a save corruption that's causing it.

**Comment by Xhanesage** [comment] 2019-10-10 00:55
One sec

**Comment by Xhanesage** [comment] 2019-10-10 01:00
Hmm I cant seem to find a way to put my save file up here

**Comment by Xhanesage** [comment] 2019-10-10 01:15
Is there a way to do it that I am not seeing? I found it but I cant copy it over or find it when I open the file upload.

**Comment by ShadowOfNight** [comment] 2019-10-10 01:35
![image](https://user-images.githubusercontent.com/36479507/66532248-b1e83280-eadc-11e9-9564-495347054770.png)

did you try dropping the file onto this?  or clicking it and navigating to where the save file is?

**Comment by Xhanesage** [comment] 2019-10-10 02:04
I did it would not let me drag the file or let me find it in the file upload.

**Comment by ShadowOfNight** [comment] 2019-10-10 02:06
Oh my bad.  create a .zip of it and resend.  that should do the trick

**Comment by Xhanesage** [comment] 2019-10-10 02:07
Oh ok got ya.

**Comment by Xhanesage** [comment] 2019-10-10 02:23
[player2.zip](https://github.com/TheLegendOfMataNui/game-issues/files/3710171/player2.zip)

**Comment by Xhanesage** [comment] 2019-10-10 02:23
There it is!

**Comment by ShadowOfNight** [comment] 2019-10-10 02:29
Yeah you have 101 tokens in this save.  The problem is in the current patch any more than 100 causes a crash when the game tries to load a save file.  This thankfully was fixed and will be released as part of the upcoming hotfix for Rebuilt.

**Comment by Xhanesage** [comment] 2019-10-10 02:31
Ok so will I need to start over or will this patch fix it? I'm fine with
either way.

**Comment by ShadowOfNight** [comment] 2019-10-10 02:39
This upcoming patch will fix it.  If you want to keep playing in the meantime you can rename that save file or move it somewhere so the game doesn't try loading it and crashing.  Again, the patch will allow that save file to work correctly.

**Comment by Xhanesage** [comment] 2019-10-10 02:57
Awesomeness thank you. I appreciate you guys so much for bringing the game taken away from our childhood to life!

**Closed as completed** 2020-01-19 16:01 UTC
Labels: Resolved

**Comment by fhuewhd** [comment] 2022-01-05 23:48
I am having what appears to be this error, but I only downloaded the program yesterday.  Shouldn't it be fixed?  Version is 1.0.1 if "versionop.txt" is accurate.  Here's a copy of my savefile, too, in case it's any use to you.
[data.zip](https://github.com/TheLegendOfMataNui/game-issues/files/7818428/data.zip)

**Comment by fhuewhd** [comment] 2022-01-05 23:52
Also, deleting the save files doesn't seem to fix the problem.

**Comment by ShadowOfNight** [comment] 2022-01-07 15:20
> I am having what appears to be this error, but I only downloaded the program yesterday. Shouldn't it be fixed? Version is 1.0.1 if "versionop.txt" is accurate. Here's a copy of my savefile, too, in case it's any use to you. [data.zip](https://github.com/TheLegendOfMataNui/game-issues/files/7818428/data.zip)

@fhuewhd This issue you posted in doesn't appear to be your problem.  Neither save you posted has a token count above 100, and this issue is for the 100+ token crash.
