### ISSUE TITLE
Crash when trying to dig through a wall in the Nui-Jaga cave

### ISSUE THREAD

**Issue by Leumeister** [TheLegendOfMataNui/game-issues#214] opened 2018-11-03 09:01 UTC
**Build Version:**

0.006 Alpha

**Steps to Reproduce:**

Get to the Nui-Jaga cave, it should save (because I'm consistantly spawning in there), load the game fron the debug main menu, and look on the wall past the first little scorpion near the entrance to the main cave. There should be a diggable wall on the right hand side between four elemental energy pickups. Begin digging the wall, whether the Pakari is active or not, and when you go in a little bit. the game goes black and closes to desktop. Also occurs when you leave that room and come back.

**Comment by OndrikB** [comment] 2018-11-03 09:02
This is a duplicate of #7. Please check all issues if they have been reported before, both open and closed

**Closed as completed by OndrikB** 2018-11-03 09:02 UTC
Labels: Duplicate Issue

**Comment by Leumeister** [comment] 2018-11-03 09:05
Okay, thank you.
