### ISSUE TITLE
Accessing an "inventory" after picking kanohi Ruru freezes the game

### ISSUE THREAD

**Issue by spmoc045** [TheLegendOfMataNui/game-issues#250] opened 2019-04-04 00:31 UTC
Beta, after saving a village

**Comment by OndrikB** [comment] 2019-04-04 00:33
Needs more information

**Comment by spmoc045** [comment] 2019-04-04 00:35
I entered pzzl from atrm's side, beat it and picked the mask.

**Comment by OndrikB** [comment] 2019-04-04 00:35
And the inventory screen just didn’t show up?

**Comment by spmoc045** [comment] 2019-04-04 00:37
Yes. On alt+tab screen the game was shown as working fine, but in-game i just can't do anything other than closing it

**Comment by OndrikB** [comment] 2019-04-04 00:39
Okay, then I’m closing this as a duplicate of #49

**Closed as completed by OndrikB** 2019-04-04 00:39 UTC
Labels: Duplicate Issue
