### ISSUE TITLE
Trigger planes and boxes are not displayed by bounding box debug mode

### ISSUE THREAD

**Issue by ShadowOfNight** [TheLegendOfMataNui/game-issues#231] opened 2019-01-04 22:39 UTC
Making these visible in a similar manner to the bounding boxes would be extremely helpful for positioning them correctly.

If at all possible, this should be done in a way to allow them to be shown independently of the bounding box mode.

**Comment by Vahkiti** [comment] 2019-01-05 02:35
Duplicate of #218

**Closed as completed by Vahkiti** 2019-01-05 02:35 UTC
Labels: Duplicate Issue
