### ISSUE TITLE
Using grappling hook while swimming crashes the game

### ISSUE THREAD

**Issue by Sam-the-Starman** [TheLegendOfMataNui/game-issues#288] opened 2020-12-18 21:05 UTC
**Build Version:**
Rebuilt

**Information:**
Using the grappling hook while underwater is disabled, like someone said in a previous issue, but i'm still able to use it while I'm swimming on the surface of the water, which causes the player to be sent somewhere out of bounds, die, and then the game crashes.

**Comment by Vahkiti** [comment] 2021-06-17 19:35
Duplicate of #287

**Closed as completed by Vahkiti** 2021-06-17 19:35 UTC
Labels: Duplicate Issue
