### ISSUE TITLE
Gali Level Incredibly Unstable (REBUILT)

### ISSUE THREAD

**Issue by Shashummga** [TheLegendOfMataNui/game-issues#290] opened 2021-03-16 22:33 UTC
For some reason, Doing near anything in Gali's level causes the game to crash. Using the hook underwater crashes the game, Drowning crashes the game and even diving into the water occasionally crashes the game.

Is there a patch or something I don't know of?

**Comment by LennyTheBionicleLover** [comment] 2021-03-19 01:03
Yeah. That’s my problem, too. Gali’s level has some problems, like the crashing whenever you re-enter the cave where you got the grappling hook, and when you use the hook underwater. It’s a bit fuzzy. Not to mention when you explore Ga-Koro, movement is running slow, even for dancing cutscenes.

**Comment by Vahkiti** [comment] 2021-06-17 19:30
Most of this will be fixed in REBUILT 1.1. Beta pernding changes.

**Comment by Vahkiti** [comment] 2021-06-17 19:35
Duplicate of #287

**Closed as completed by Vahkiti** 2021-06-17 19:35 UTC
Labels: Duplicate Issue
