### ISSUE TITLE
ta14 exit crash

### ISSUE THREAD

**Issue by spmoc045** [TheLegendOfMataNui/game-issues#249] opened 2019-04-02 06:53 UTC
Error 0057c7fb

Alpha

**Comment by OndrikB** [comment] 2019-04-02 07:01
Known, duplicate of #16 and #17

**Comment by ShadowOfNight** [comment] 2019-04-02 22:11
Located and corrected the script error that was causing the crash.  Fix will be included in the next alpha patch; marking as resolved and closing this issue.

**Closed as completed by ShadowOfNight** 2019-04-02 22:11 UTC
Labels: Crash, Exception, Resolved, Build: Alpha 0.006
