### ISSUE TITLE
Inventory crashes game

### ISSUE THREAD

**Issue by fedorastories** [TheLegendOfMataNui/game-issues#280] opened 2020-04-25 18:37 UTC
**Remember to add the following information:**

**Build Version:**

Rebuild

**Steps to Reproduce:**

It's random. I've only made it through Onua's level, but accessing the inventory often crashes the game.

**Comment by ReeseWB-001** [comment] 2020-05-04 19:45
What's the crash address?

**Comment by LennyTheBionicleLover** [comment] 2020-09-11 06:23
I have that problem, too. It happened when I was playing Onua in Onu-Koro, I was checking my Inventory, but then it froze, and I couldn’t move. :(

**Comment by LennyTheBionicleLover** [comment] 2020-09-11 20:03
Same happened with Pohatu’s level. :(

**Comment by ReeseWB-001** [comment] 2020-09-11 23:28
Duplicate of #49 .

**Closed as completed by ReeseWB-001** 2020-09-11 23:28 UTC
Labels: Duplicate Issue
