### ISSUE TITLE
Softlock on Pohatu level after bull run

### ISSUE THREAD

**Issue by thirtyspeed** [TheLegendOfMataNui/game-issues#275] opened 2019-11-24 18:35 UTC
Rebuilt 1.0.0 (seems to be continued in 1.0.1 but my launcher can't seem to update properly, and I believe the save is already corrupted at this point.)

After completing the Bull run in Pohatu's part, and after defeating the stone elemental & getting Onewa's (?) mask, upon exiting the maze-cave to return to po-koro the game crashes, and autosaves creating a crash-on-load corrupted save.

**Comment by Vahkiti** [comment] 2019-11-26 17:42
Hi there! What seems to be wrong with your launcher first off? Secondly, can you detail exactly what you're doing in what order to achieve this softlock? It's not exactly clear to me. Are you going all the way through to the Makoki Stone then trying to backtrack to Po-Koro?

**Comment by thirtyspeed** [comment] 2019-11-28 01:02
Onua is showing up in the menu, so I believe the patch was applied, but it asks to redownload the patch every time I relaunch, making it unclear whether it was successful or not.

As far as what I did, I talked to the turaga after doing the dance with the touhunga/matoran who said I had to find the mask, I go do the boulder shooting thing (which goes on for an incredibly long time, to my surprise) and then ride the bull for a while before it dumps you off at the stone elemental's chamber. You fight it, die, try again but this time it's stuck in place (lol I know this is also a known bug) and grab the mask in its chamber. Once you try to exit and return to Po-Koro it crashes. When you load the save again, it tries to load the same Po-Koro warp and crashes every time.

**Comment by Vahkiti** [comment] 2021-06-17 19:39
Is this still relevant as of 1.0.2?

**Comment by ShadowOfNight** [comment] 2022-01-05 19:58
@thirtyspeed is this still an issue for you?

**Comment by ShadowOfNight** [comment] 2022-12-23 18:47
@thirtyspeed Is this still a problem for you on the latest launcher and the current version of Rebuilt (v1.1)?

**Comment by ShadowOfNight** [comment] 2023-11-27 22:24
Due to lack of replies and inability to reproduce on our end, I'm closing this issue down.  If you or anyone else encounters this again feel free to comment or open a new ticket.

**Closed as not planned by ShadowOfNight** 2023-11-27 22:24 UTC
Labels: Level-3 Pohatu, Needs Information, Resolved, Build: "Beta" 10-23-01, Rebuilt Patch
